application:
  version: 1.2.1


spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
        uri: ${DB:mongodb://anon:pass123@ds123171.mlab.com:23171/heroku_rsdc1cd0}

---
spring:
  profiles: dev


---
spring:
  profiles: sandbox


---
spring:
  profiles: production